# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "MatsSocket: Mats3 over Websocket"
masthead_title: MatsSocket
subtitle: Mats<sup>3</sup> over WebSocket
logo: /assets/images/MatsSocketLogo.svg
name: Endre Stølsvik
email: endre@stolsvik.com
description: >-
  MatsSocket pulls Mats3 all the way out to the client!
url: https://centiservice.com
minimal_mistakes_skin: dark
search: true
search_full_content: true

# Localhost development port when using 'serve'
port: 4001

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 50 # amount of posts to show
#paginate_path: /page:num/
timezone: Europe/Oslo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
#  - javadoc

# Exclude from processing.
exclude:
  - EndreXY*
  - copy_*
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Social Sharing
twitter:
  username: stolsvik
og_image: /assets/images/MatsSocketLogo-640x640.png   # Open Graph/Twitter default site image
# EndreXY 2022-08-07: Based on https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# .. to fix the problem "GitHub Metadata: No GitHub API authentication could be found.
#     Some fields may be missing or have incorrect data."
github: [metadata]
github_username: stolsvik
repository: centiservice/matssocket
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: Organization
  name: Centiservice
#  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-ZJLPFZNW2N"
    anonymize_ip         : false

author:
  name   : "Endre Stølsvik"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Creator of Mats3 & MatsSocket"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://centiservice.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/stolsvik"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stolsvik"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/stolsvik"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/centiservice"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
